export const stocks = [
  { Ticker: "AAPL", Company: "Apple Inc. Common Stock" },
  { Ticker: "ABNB", Company: "Airbnb, Inc. Class A Common Stock" },
  { Ticker: "ADBE", Company: "Adobe Inc. Common Stock" },
  { Ticker: "ADI", Company: "Analog Devices, Inc. Common Stock" },
  { Ticker: "ADP", Company: "Automatic Data Processing, Inc. Common Stock" },
  { Ticker: "ADSK", Company: "Autodesk, Inc. Common Stock" },
  {
    Ticker: "AEP",
    Company: "American Electric Power Company, Inc. Common Stock",
  },
  { Ticker: "ALGN", Company: "Align Technology, Inc. Common Stock" },
  { Ticker: "AMAT", Company: "Applied Materials, Inc. Common Stock" },
  { Ticker: "AMD", Company: "Advanced Micro Devices, Inc. Common Stock" },
  { Ticker: "AMGN", Company: "Amgen Inc. Common Stock" },
  { Ticker: "AMZN", Company: "Amazon.com, Inc. Common Stock" },
  { Ticker: "ANSS", Company: "ANSYS, Inc. Common Stock" },
  { Ticker: "ASML", Company: "ASML Holding N.V. New York Registry Shares" },
  { Ticker: "ATVI", Company: "Activision Blizzard, Inc. Common Stock" },
  { Ticker: "AVGO", Company: "Broadcom Inc. Common Stock" },
  { Ticker: "AZN", Company: "AstraZeneca PLC American Depositary Shares" },
  { Ticker: "BIDU", Company: "Baidu, Inc. ADS" },
  { Ticker: "BIIB", Company: "Biogen Inc. Common Stock" },
  { Ticker: "BKNG", Company: "Booking Holdings Inc. Common Stock" },
  { Ticker: "CDNS", Company: "Cadence Design Systems, Inc. Common Stock" },
  { Ticker: "CEG", Company: "Constellation Energy Corporation Common Stock" },
  {
    Ticker: "CHTR",
    Company: "Charter Communications, Inc. Class A Common Stock New",
  },
  { Ticker: "CMCSA", Company: "Comcast Corporation Class A Common Stock" },
  { Ticker: "COST", Company: "Costco Wholesale Corporation Common Stock" },
  { Ticker: "CPRT", Company: "Copart, Inc. (DE) Common Stock" },
  {
    Ticker: "CRWD",
    Company: "CrowdStrike Holdings, Inc. Class A Common Stock",
  },
  { Ticker: "CSCO", Company: "Cisco Systems, Inc. Common Stock (DE)" },
  { Ticker: "CSX", Company: "CSX Corporation Common Stock" },
  { Ticker: "CTAS", Company: "Cintas Corporation Common Stock" },
  {
    Ticker: "CTSH",
    Company: "Cognizant Technology Solutions Corporation Class A Common Stock",
  },
  { Ticker: "DDOG", Company: "Datadog, Inc. Class A Common Stock" },
  { Ticker: "DLTR", Company: "Dollar Tree Inc. Common Stock" },
  { Ticker: "DOCU", Company: "DocuSign, Inc. Common Stock" },
  { Ticker: "DXCM", Company: "DexCom, Inc. Common Stock" },
  { Ticker: "EA", Company: "Electronic Arts Inc. Common Stock" },
  { Ticker: "EBAY", Company: "eBay Inc. Common Stock" },
  { Ticker: "EXC", Company: "Exelon Corporation Common Stock" },
  { Ticker: "FAST", Company: "Fastenal Company Common Stock" },
  { Ticker: "FISV", Company: "Fiserv, Inc. Common Stock" },
  { Ticker: "FTNT", Company: "Fortinet, Inc. Common Stock" },
  { Ticker: "GILD", Company: "Gilead Sciences, Inc. Common Stock" },
  { Ticker: "GOOG", Company: "Alphabet Inc. Class C Capital Stock" },
  { Ticker: "GOOGL", Company: "Alphabet Inc. Class A Common Stock" },
  { Ticker: "HON", Company: "Honeywell International Inc. Common Stock" },
  { Ticker: "IDXX", Company: "IDEXX Laboratories, Inc. Common Stock" },
  { Ticker: "ILMN", Company: "Illumina, Inc. Common Stock" },
  { Ticker: "INTC", Company: "Intel Corporation Common Stock" },
  { Ticker: "INTU", Company: "Intuit Inc. Common Stock" },
  { Ticker: "ISRG", Company: "Intuitive Surgical, Inc. Common Stock" },
  { Ticker: "JD", Company: "JD.com, Inc. American Depositary Shares" },
  { Ticker: "KDP", Company: "Keurig Dr Pepper Inc. Common Stock" },
  { Ticker: "KHC", Company: "The Kraft Heinz Company Common Stock" },
  { Ticker: "KLAC", Company: "KLA Corporation Common Stock" },
  { Ticker: "LCID", Company: "Lucid Group, Inc. Common Stock" },
  { Ticker: "LRCX", Company: "Lam Research Corporation Common Stock" },
  { Ticker: "LULU", Company: "lululemon athletica inc. Common Stock" },
  { Ticker: "MAR", Company: "Marriott International Class A Common Stock" },
  { Ticker: "MCHP", Company: "Microchip Technology Incorporated Common Stock" },
  {
    Ticker: "MDLZ",
    Company: "Mondelez International, Inc. Class A Common Stock",
  },
  { Ticker: "MELI", Company: "MercadoLibre, Inc. Common Stock" },
  { Ticker: "META", Company: "Meta Platforms, Inc. Class A Common Stock" },
  { Ticker: "MNST", Company: "Monster Beverage Corporation" },
  { Ticker: "MRNA", Company: "Moderna, Inc. Common Stock" },
  { Ticker: "MRVL", Company: "Marvell Technology, Inc. Common Stock" },
  { Ticker: "MSFT", Company: "Microsoft Corporation Common Stock" },
  { Ticker: "MTCH", Company: "Match Group, Inc. Common Stock" },
  { Ticker: "MU", Company: "Micron Technology, Inc. Common Stock" },
  { Ticker: "NFLX", Company: "Netflix, Inc. Common Stock" },
  { Ticker: "NTES", Company: "NetEase, Inc. American Depositary Shares" },
  { Ticker: "NVDA", Company: "NVIDIA Corporation Common Stock" },
  { Ticker: "NXPI", Company: "NXP Semiconductors N.V. Common Stock" },
  { Ticker: "ODFL", Company: "Old Dominion Freight Line, Inc. Common Stock" },
  { Ticker: "OKTA", Company: "Okta, Inc. Class A Common Stock" },
  { Ticker: "ORLY", Company: "O'Reilly Automotive, Inc. Common Stock" },
  { Ticker: "PANW", Company: "Palo Alto Networks, Inc. Common Stock" },
  { Ticker: "PAYX", Company: "Paychex, Inc. Common Stock" },
  { Ticker: "PCAR", Company: "PACCAR Inc. Common Stock" },
  { Ticker: "PDD", Company: "Pinduoduo Inc. American Depositary Shares" },
  { Ticker: "PEP", Company: "PepsiCo, Inc. Common Stock" },
  { Ticker: "PYPL", Company: "PayPal Holdings, Inc. Common Stock" },
  { Ticker: "QCOM", Company: "QUALCOMM Incorporated Common Stock" },
  { Ticker: "REGN", Company: "Regeneron Pharmaceuticals, Inc. Common Stock" },
  { Ticker: "ROST", Company: "Ross Stores, Inc. Common Stock" },
  { Ticker: "SBUX", Company: "Starbucks Corporation Common Stock" },
  { Ticker: "SGEN", Company: "Seagen Inc. Common Stock" },
  { Ticker: "SIRI", Company: "Sirius XM Holdings Inc. Common Stock" },
  { Ticker: "SNPS", Company: "Synopsys, Inc. Common Stock" },
  { Ticker: "SPLK", Company: "Splunk Inc. Common Stock" },
  { Ticker: "SWKS", Company: "Skyworks Solutions, Inc. Common Stock" },
  {
    Ticker: "TEAM",
    Company: "Atlassian Corporation Plc Class A Ordinary Shares",
  },
  { Ticker: "TMUS", Company: "T-Mobile US, Inc. Common Stock" },
  { Ticker: "TSLA", Company: "Tesla, Inc. Common Stock" },
  { Ticker: "TXN", Company: "Texas Instruments Incorporated Common Stock" },
  { Ticker: "VRSK", Company: "Verisk Analytics, Inc. Common Stock" },
  { Ticker: "VRSN", Company: "VeriSign, Inc. Common Stock" },
  {
    Ticker: "VRTX",
    Company: "Vertex Pharmaceuticals Incorporated Common Stock",
  },
  { Ticker: "WBA", Company: "Walgreens Boots Alliance, Inc. Common Stock" },
  { Ticker: "WDAY", Company: "Workday, Inc. Class A Common Stock" },
  { Ticker: "XEL", Company: "Xcel Energy Inc. Common Stock" },
  {
    Ticker: "ZM",
    Company: "Zoom Video Communications, Inc. Class A Common Stock",
  },
  { Ticker: "ZS", Company: "Zscaler, Inc. Common Stock" },
];
